node_js:
- 8
 
env:
  global:
    - GIT_NAME: elcharitas
    - GIT_EMAIL: jonathanirhodia@gmail.com
    - GITHUB_REPO: elcharitas/waxe
    - GIT_SOURCE: docs/_dist
 
script:
- npm install
 
after_success:
- npm test
- npm run lint